spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false
servers:
  - www.abc.test.com
  - www.xyz.test.com

url:jdbc:mysql://mydb:
  123456789012:
    us-east-1:
      rds:
        amazonaws:
          com:3306/myTestDB?autoReconnect=true&useSSL=false:

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - www.abc.com
  - www.xyz.com