spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false
servers:
  - www.abc.test.com
  - www.xyz.test.com

url:jdbc:mysql://mydb:
  123456789012:
    us-east-1:
      rds:
        amazonaws:
          com:3306/myTestDB?autoReconnect=true&useSSL=false:

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - www.abc.com
  - www.xyz.com
datasource:
  password: password
  url: jdbc:h2:dev
  username: SA